# Generated by Django 2.2 on 2023-07-17 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0002_auto_20230717_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovotostest',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votaciones.RegionesTest'),
        ),
    ]
