# Generated by Django 2.2 on 2023-07-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0003_registrovotostest_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinnastest',
            options={'managed': True},
        ),
    ]
