# Generated by Django 2.2 on 2023-07-25 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0004_auto_20230725_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinnastest',
            name='vinna_descripcion',
            field=models.CharField(default='Aqui va una breve descripción de la viña, ejemplo donde esta ubicada y demas', max_length=120),
        ),
        migrations.AddField(
            model_name='vinnastest',
            name='vinna_titulo',
            field=models.CharField(default='Titulo viña', max_length=120),
        ),
        migrations.AddField(
            model_name='vinnastest',
            name='vinna_url_img_md',
            field=models.CharField(default='https://st.depositphotos.com/1000423/60623/i/600/depositphotos_606236826-stock-photo-nanotechnology-molecule-and-atom-model.jpg', max_length=200),
        ),
    ]
